export interface WordEntry {
  word: string;
  clue: string;
}

/**
 * Curated word bank for 5×5 mini crosswords.
 * Words are 3–5 letters, common English, with simple clues.
 */
export const WORD_BANK: WordEntry[] = [
  // ── 3-letter words ──────────────────────────────────────────────
  { word: "ACE", clue: "Top card" },
  { word: "ACT", clue: "Perform on stage" },
  { word: "ADD", clue: "Sum up" },
  { word: "AGE", clue: "How old you are" },
  { word: "AID", clue: "Help" },
  { word: "AIM", clue: "Point at a target" },
  { word: "AIR", clue: "What we breathe" },
  { word: "ALE", clue: "Pub drink" },
  { word: "APE", clue: "Gorilla or chimp" },
  { word: "ARC", clue: "Curved line" },
  { word: "ARK", clue: "Noah's vessel" },
  { word: "ARM", clue: "Body limb" },
  { word: "ART", clue: "Museum display" },
  { word: "ATE", clue: "Had a meal" },
  { word: "AWE", clue: "Wonder and amazement" },
  { word: "AXE", clue: "Chopping tool" },
  { word: "BAD", clue: "Not good" },
  { word: "BAG", clue: "Carry-all" },
  { word: "BAN", clue: "Prohibit" },
  { word: "BAR", clue: "Pub counter" },
  { word: "BAT", clue: "Cricket stick" },
  { word: "BED", clue: "Sleep spot" },
  { word: "BET", clue: "Wager" },
  { word: "BIG", clue: "Large" },
  { word: "BIT", clue: "Small piece" },
  { word: "BOW", clue: "Archery tool" },
  { word: "BOX", clue: "Cardboard container" },
  { word: "BOY", clue: "Young lad" },
  { word: "BUD", clue: "Flower before bloom" },
  { word: "BUG", clue: "Insect" },
  { word: "BUN", clue: "Bread roll" },
  { word: "BUS", clue: "Public transport" },
  { word: "BUT", clue: "However" },
  { word: "BUY", clue: "Purchase" },
  { word: "CAB", clue: "Taxi" },
  { word: "CAN", clue: "Tin container" },
  { word: "CAP", clue: "Hat" },
  { word: "CAR", clue: "Automobile" },
  { word: "CAT", clue: "Feline pet" },
  { word: "COP", clue: "Police officer" },
  { word: "COT", clue: "Baby bed" },
  { word: "COW", clue: "Dairy animal" },
  { word: "CRY", clue: "Shed tears" },
  { word: "CUB", clue: "Young bear" },
  { word: "CUP", clue: "Tea vessel" },
  { word: "CUT", clue: "Snip" },
  { word: "DAD", clue: "Father" },
  { word: "DAM", clue: "River barrier" },
  { word: "DAY", clue: "24 hours" },
  { word: "DEN", clue: "Bear's lair" },
  { word: "DEW", clue: "Morning moisture" },
  { word: "DIG", clue: "Excavate" },
  { word: "DIM", clue: "Not bright" },
  { word: "DIP", clue: "Quick swim" },
  { word: "DOG", clue: "Man's best friend" },
  { word: "DOT", clue: "Tiny spot" },
  { word: "DRY", clue: "Not wet" },
  { word: "DUB", clue: "Name or title" },
  { word: "DUE", clue: "Owed" },
  { word: "DUG", clue: "Excavated" },
  { word: "DYE", clue: "Color changer" },
  { word: "EAR", clue: "Hearing organ" },
  { word: "EAT", clue: "Consume food" },
  { word: "EEL", clue: "Slippery fish" },
  { word: "EGG", clue: "Breakfast oval" },
  { word: "ELF", clue: "Santa's helper" },
  { word: "ELM", clue: "Shade tree" },
  { word: "EMU", clue: "Flightless bird" },
  { word: "END", clue: "Finish" },
  { word: "ERA", clue: "Time period" },
  { word: "EVE", clue: "Night before" },
  { word: "EWE", clue: "Female sheep" },
  { word: "EYE", clue: "Sight organ" },
  { word: "FAN", clue: "Cool breeze maker" },
  { word: "FAR", clue: "Not near" },
  { word: "FAT", clue: "Opposite of thin" },
  { word: "FAX", clue: "Send a document" },
  { word: "FED", clue: "Gave food to" },
  { word: "FEW", clue: "Not many" },
  { word: "FIG", clue: "Sweet fruit" },
  { word: "FIN", clue: "Fish flipper" },
  { word: "FIT", clue: "In good shape" },
  { word: "FIX", clue: "Repair" },
  { word: "FLY", clue: "Soar through air" },
  { word: "FOB", clue: "Key chain" },
  { word: "FOG", clue: "Thick mist" },
  { word: "FOR", clue: "In favor of" },
  { word: "FOX", clue: "Cunning animal" },
  { word: "FRY", clue: "Cook in oil" },
  { word: "FUN", clue: "Good time" },
  { word: "FUR", clue: "Animal coat" },
  { word: "GAP", clue: "Opening" },
  { word: "GAS", clue: "Fuel" },
  { word: "GEL", clue: "Hair product" },
  { word: "GEM", clue: "Precious stone" },
  { word: "GET", clue: "Obtain" },
  { word: "GIG", clue: "Music show" },
  { word: "GIN", clue: "Cocktail spirit" },
  { word: "GNU", clue: "African antelope" },
  { word: "GOD", clue: "Divine being" },
  { word: "GOT", clue: "Obtained" },
  { word: "GUM", clue: "Chewing treat" },
  { word: "GUN", clue: "Firearm" },
  { word: "GUT", clue: "Stomach" },
  { word: "GUY", clue: "Fellow" },
  { word: "GYM", clue: "Workout place" },
  { word: "HAD", clue: "Possessed" },
  { word: "HAM", clue: "Pork cut" },
  { word: "HAS", clue: "Possesses" },
  { word: "HAT", clue: "Head cover" },
  { word: "HEN", clue: "Female chicken" },
  { word: "HER", clue: "Belonging to she" },
  { word: "HEW", clue: "Chop with an axe" },
  { word: "HID", clue: "Concealed" },
  { word: "HIM", clue: "Masculine pronoun" },
  { word: "HIP", clue: "Trendy" },
  { word: "HIT", clue: "Strike" },
  { word: "HOG", clue: "Pig" },
  { word: "HOP", clue: "Small jump" },
  { word: "HOT", clue: "Very warm" },
  { word: "HOW", clue: "In what way" },
  { word: "HUB", clue: "Central point" },
  { word: "HUE", clue: "Color shade" },
  { word: "HUG", clue: "Warm embrace" },
  { word: "HUM", clue: "Sing without words" },
  { word: "HUT", clue: "Small shelter" },
  { word: "ICE", clue: "Frozen water" },
  { word: "ILL", clue: "Unwell" },
  { word: "IMP", clue: "Mischievous sprite" },
  { word: "INK", clue: "Pen fluid" },
  { word: "INN", clue: "Small hotel" },
  { word: "ION", clue: "Charged atom" },
  { word: "IRE", clue: "Anger" },
  { word: "IVY", clue: "Climbing plant" },
  { word: "JAB", clue: "Quick punch" },
  { word: "JAM", clue: "Fruit spread" },
  { word: "JAR", clue: "Glass container" },
  { word: "JAW", clue: "Mouth bone" },
  { word: "JAY", clue: "Blue bird" },
  { word: "JET", clue: "Fast plane" },
  { word: "JOB", clue: "Employment" },
  { word: "JOG", clue: "Slow run" },
  { word: "JOT", clue: "Quick note" },
  { word: "JOY", clue: "Happiness" },
  { word: "JUG", clue: "Water pitcher" },
  { word: "KEY", clue: "Door opener" },
  { word: "KID", clue: "Child" },
  { word: "KIN", clue: "Family" },
  { word: "KIT", clue: "Set of tools" },
  { word: "LAB", clue: "Science room" },
  { word: "LAD", clue: "Young boy" },
  { word: "LAP", clue: "Track circuit" },
  { word: "LAW", clue: "Legal rule" },
  { word: "LAY", clue: "Put down" },
  { word: "LED", clue: "Guided" },
  { word: "LEG", clue: "Walking limb" },
  { word: "LET", clue: "Allow" },
  { word: "LID", clue: "Container top" },
  { word: "LIE", clue: "Untruth" },
  { word: "LIP", clue: "Mouth edge" },
  { word: "LOG", clue: "Wood piece" },
  { word: "LOT", clue: "A great deal" },
  { word: "LOW", clue: "Not high" },
  { word: "MAD", clue: "Angry" },
  { word: "MAN", clue: "Adult male" },
  { word: "MAP", clue: "Navigation chart" },
  { word: "MAT", clue: "Floor covering" },
  { word: "MAX", clue: "Maximum" },
  { word: "MAY", clue: "Month after April" },
  { word: "MIX", clue: "Blend together" },
  { word: "MOB", clue: "Unruly crowd" },
  { word: "MOP", clue: "Floor cleaner" },
  { word: "MUD", clue: "Wet earth" },
  { word: "MUG", clue: "Coffee cup" },
  { word: "NAB", clue: "Catch" },
  { word: "NAP", clue: "Short sleep" },
  { word: "NET", clue: "Fish catcher" },
  { word: "NEW", clue: "Not old" },
  { word: "NIT", clue: "Tiny complaint" },
  { word: "NOD", clue: "Head gesture" },
  { word: "NOR", clue: "And not" },
  { word: "NOT", clue: "Negative" },
  { word: "NOW", clue: "At this moment" },
  { word: "NUB", clue: "Core point" },
  { word: "NUN", clue: "Convent member" },
  { word: "NUT", clue: "Hard-shelled snack" },
  { word: "OAK", clue: "Sturdy tree" },
  { word: "OAR", clue: "Rowing tool" },
  { word: "OAT", clue: "Cereal grain" },
  { word: "ODD", clue: "Strange" },
  { word: "OIL", clue: "Cooking liquid" },
  { word: "OLD", clue: "Not young" },
  { word: "ONE", clue: "Single" },
  { word: "OPT", clue: "Choose" },
  { word: "ORB", clue: "Sphere" },
  { word: "ORE", clue: "Mineral deposit" },
  { word: "OUR", clue: "Belonging to us" },
  { word: "OUT", clue: "Not in" },
  { word: "OWE", clue: "Be in debt" },
  { word: "OWL", clue: "Night bird" },
  { word: "OWN", clue: "Possess" },
  { word: "PAD", clue: "Writing tablet" },
  { word: "PAN", clue: "Frying vessel" },
  { word: "PAT", clue: "Gentle tap" },
  { word: "PAW", clue: "Dog's foot" },
  { word: "PEA", clue: "Green veggie" },
  { word: "PEN", clue: "Writing tool" },
  { word: "PET", clue: "House animal" },
  { word: "PIE", clue: "Baked dessert" },
  { word: "PIG", clue: "Farm animal" },
  { word: "PIN", clue: "Sharp fastener" },
  { word: "PIT", clue: "Deep hole" },
  { word: "PLY", clue: "Layer of wood" },
  { word: "POD", clue: "Pea casing" },
  { word: "POP", clue: "Music genre" },
  { word: "POT", clue: "Cooking vessel" },
  { word: "PUB", clue: "Local bar" },
  { word: "PUN", clue: "Play on words" },
  { word: "PUP", clue: "Young dog" },
  { word: "PUT", clue: "Place" },
  { word: "RAG", clue: "Old cloth" },
  { word: "RAM", clue: "Male sheep" },
  { word: "RAN", clue: "Sprinted" },
  { word: "RAP", clue: "Music style" },
  { word: "RAT", clue: "Rodent" },
  { word: "RAW", clue: "Uncooked" },
  { word: "RAY", clue: "Beam of light" },
  { word: "RED", clue: "Fire truck color" },
  { word: "REF", clue: "Game official" },
  { word: "RIB", clue: "Chest bone" },
  { word: "RID", clue: "Free from" },
  { word: "RIG", clue: "Oil platform" },
  { word: "RIM", clue: "Edge of a cup" },
  { word: "RIP", clue: "Tear apart" },
  { word: "ROB", clue: "Steal from" },
  { word: "ROD", clue: "Fishing pole" },
  { word: "ROT", clue: "Decay" },
  { word: "ROW", clue: "Line of seats" },
  { word: "RUB", clue: "Massage" },
  { word: "RUG", clue: "Floor carpet" },
  { word: "RUN", clue: "Sprint" },
  { word: "RUT", clue: "Groove in road" },
  { word: "SAD", clue: "Unhappy" },
  { word: "SAP", clue: "Tree fluid" },
  { word: "SAT", clue: "Was seated" },
  { word: "SAW", clue: "Cutting tool" },
  { word: "SAY", clue: "Speak" },
  { word: "SEA", clue: "Ocean" },
  { word: "SET", clue: "Group" },
  { word: "SEW", clue: "Stitch fabric" },
  { word: "SHE", clue: "Female pronoun" },
  { word: "SHY", clue: "Timid" },
  { word: "SIP", clue: "Drink slowly" },
  { word: "SIT", clue: "Take a seat" },
  { word: "SIX", clue: "Half a dozen" },
  { word: "SKI", clue: "Snow sport" },
  { word: "SKY", clue: "Above us" },
  { word: "SLY", clue: "Crafty" },
  { word: "SOB", clue: "Cry loudly" },
  { word: "SOD", clue: "Grass turf" },
  { word: "SON", clue: "Male child" },
  { word: "SOP", clue: "Soaked morsel" },
  { word: "SOW", clue: "Plant seeds" },
  { word: "SOY", clue: "Bean sauce" },
  { word: "SPA", clue: "Relaxation spot" },
  { word: "SPY", clue: "Secret agent" },
  { word: "STY", clue: "Pig pen" },
  { word: "SUB", clue: "Substitute" },
  { word: "SUM", clue: "Total" },
  { word: "SUN", clue: "Our star" },
  { word: "TAB", clue: "Browser window" },
  { word: "TAG", clue: "Price label" },
  { word: "TAN", clue: "Sun color" },
  { word: "TAP", clue: "Light touch" },
  { word: "TAR", clue: "Road coating" },
  { word: "TAX", clue: "Government levy" },
  { word: "TEA", clue: "Hot beverage" },
  { word: "TEN", clue: "Decade number" },
  { word: "THE", clue: "Common article" },
  { word: "TIE", clue: "Neck wear" },
  { word: "TIN", clue: "Metal can" },
  { word: "TIP", clue: "Helpful hint" },
  { word: "TOE", clue: "Foot digit" },
  { word: "TON", clue: "Heavy weight" },
  { word: "TOO", clue: "Also" },
  { word: "TOP", clue: "Highest point" },
  { word: "TOW", clue: "Pull along" },
  { word: "TOY", clue: "Child's plaything" },
  { word: "TUB", clue: "Bath vessel" },
  { word: "TUG", clue: "Pull hard" },
  { word: "TWO", clue: "A pair" },
  { word: "URN", clue: "Coffee pot" },
  { word: "USE", clue: "Employ" },
  { word: "VAN", clue: "Delivery vehicle" },
  { word: "VAT", clue: "Large tank" },
  { word: "VET", clue: "Animal doctor" },
  { word: "VIA", clue: "By way of" },
  { word: "VOW", clue: "Solemn promise" },
  { word: "WAR", clue: "Armed conflict" },
  { word: "WAX", clue: "Candle material" },
  { word: "WAY", clue: "Path" },
  { word: "WEB", clue: "Spider's creation" },
  { word: "WED", clue: "Marry" },
  { word: "WET", clue: "Not dry" },
  { word: "WHO", clue: "Which person" },
  { word: "WIG", clue: "Fake hair" },
  { word: "WIN", clue: "Victory" },
  { word: "WIT", clue: "Clever humor" },
  { word: "WOK", clue: "Asian pan" },
  { word: "WON", clue: "Was victorious" },
  { word: "WOO", clue: "Court romantically" },
  { word: "YAK", clue: "Tibetan ox" },
  { word: "YAM", clue: "Sweet potato" },
  { word: "YAP", clue: "Small bark" },
  { word: "YEW", clue: "Evergreen tree" },
  { word: "ZAP", clue: "Destroy quickly" },
  { word: "ZEN", clue: "Buddhist calm" },
  { word: "ZIP", clue: "Zip code start" },
  { word: "ZIT", clue: "Skin blemish" },
  { word: "ZOO", clue: "Animal park" },

  // ── 4-letter words ──────────────────────────────────────────────
  { word: "ABLE", clue: "Capable" },
  { word: "ACHE", clue: "Dull pain" },
  { word: "ACID", clue: "Battery fluid" },
  { word: "AGED", clue: "Old" },
  { word: "AIDE", clue: "Helper" },
  { word: "ALLY", clue: "Partner" },
  { word: "ARCH", clue: "Curved structure" },
  { word: "ARIA", clue: "Opera solo" },
  { word: "ARMY", clue: "Military force" },
  { word: "ATOM", clue: "Tiny particle" },
  { word: "AVID", clue: "Eager" },
  { word: "AXIS", clue: "Line of rotation" },
  { word: "BAKE", clue: "Oven cook" },
  { word: "BALD", clue: "Without hair" },
  { word: "BALL", clue: "Round toy" },
  { word: "BAND", clue: "Music group" },
  { word: "BANK", clue: "Money institution" },
  { word: "BARE", clue: "Uncovered" },
  { word: "BARK", clue: "Dog sound" },
  { word: "BARN", clue: "Farm building" },
  { word: "BASE", clue: "Foundation" },
  { word: "BATH", clue: "Soak in water" },
  { word: "BEAD", clue: "Necklace piece" },
  { word: "BEAM", clue: "Ray of light" },
  { word: "BEAN", clue: "Coffee seed" },
  { word: "BEAR", clue: "Forest animal" },
  { word: "BEAT", clue: "Rhythm" },
  { word: "BEEF", clue: "Steak meat" },
  { word: "BELL", clue: "Ring maker" },
  { word: "BELT", clue: "Waist band" },
  { word: "BEND", clue: "Curve" },
  { word: "BIKE", clue: "Two-wheeler" },
  { word: "BIRD", clue: "Feathered flier" },
  { word: "BITE", clue: "Chomp" },
  { word: "BLOW", clue: "Wind gust" },
  { word: "BLUE", clue: "Sky color" },
  { word: "BLUR", clue: "Out of focus" },
  { word: "BOAT", clue: "Water vessel" },
  { word: "BOLD", clue: "Brave" },
  { word: "BOLT", clue: "Lightning flash" },
  { word: "BOMB", clue: "Explosive" },
  { word: "BOND", clue: "Connection" },
  { word: "BONE", clue: "Skeleton part" },
  { word: "BOOK", clue: "Reading material" },
  { word: "BOOT", clue: "Heavy shoe" },
  { word: "BORE", clue: "Drill a hole" },
  { word: "BOSS", clue: "Manager" },
  { word: "BOWL", clue: "Soup dish" },
  { word: "BRIM", clue: "Hat edge" },
  { word: "BULB", clue: "Light source" },
  { word: "BULK", clue: "Large quantity" },
  { word: "BULL", clue: "Male cow" },
  { word: "BUMP", clue: "Small collision" },
  { word: "BURN", clue: "Fire damage" },
  { word: "CAGE", clue: "Animal enclosure" },
  { word: "CAKE", clue: "Birthday treat" },
  { word: "CALM", clue: "Peaceful" },
  { word: "CAME", clue: "Arrived" },
  { word: "CAMP", clue: "Tent site" },
  { word: "CAPE", clue: "Hero's garment" },
  { word: "CARD", clue: "Playing deck item" },
  { word: "CARE", clue: "Concern" },
  { word: "CART", clue: "Shopping trolley" },
  { word: "CASE", clue: "Suitcase" },
  { word: "CASH", clue: "Money" },
  { word: "CAVE", clue: "Underground space" },
  { word: "CHEF", clue: "Kitchen boss" },
  { word: "CHIP", clue: "Potato snack" },
  { word: "CHOP", clue: "Cut with axe" },
  { word: "CLAM", clue: "Shell creature" },
  { word: "CLAP", clue: "Applaud" },
  { word: "CLAY", clue: "Potter's material" },
  { word: "CLIP", clue: "Paper holder" },
  { word: "CLUE", clue: "Puzzle hint" },
  { word: "COAL", clue: "Black fuel" },
  { word: "COAT", clue: "Winter jacket" },
  { word: "CODE", clue: "Secret message" },
  { word: "COIL", clue: "Spiral" },
  { word: "COIN", clue: "Metal money" },
  { word: "COLD", clue: "Chilly" },
  { word: "COLT", clue: "Young horse" },
  { word: "COMB", clue: "Hair tool" },
  { word: "COOK", clue: "Prepare food" },
  { word: "COOL", clue: "Slightly cold" },
  { word: "COPE", clue: "Deal with" },
  { word: "CORD", clue: "Rope" },
  { word: "CORE", clue: "Center" },
  { word: "CORK", clue: "Bottle stopper" },
  { word: "CORN", clue: "Yellow veggie" },
  { word: "COST", clue: "Price" },
  { word: "COZY", clue: "Snug" },
  { word: "CRAB", clue: "Beach creature" },
  { word: "CREW", clue: "Ship team" },
  { word: "CROP", clue: "Farm harvest" },
  { word: "CROW", clue: "Black bird" },
  { word: "CUBE", clue: "Six-sided shape" },
  { word: "CURB", clue: "Street edge" },
  { word: "CURE", clue: "Remedy" },
  { word: "CURL", clue: "Hair wave" },
  { word: "DAMP", clue: "Slightly wet" },
  { word: "DARE", clue: "Challenge" },
  { word: "DARK", clue: "Without light" },
  { word: "DART", clue: "Throwing game" },
  { word: "DASH", clue: "Quick run" },
  { word: "DATA", clue: "Information" },
  { word: "DAWN", clue: "Sunrise time" },
  { word: "DEAL", clue: "Bargain" },
  { word: "DEAR", clue: "Beloved" },
  { word: "DECK", clue: "Card set" },
  { word: "DEED", clue: "Action" },
  { word: "DEEP", clue: "Very far down" },
  { word: "DEER", clue: "Forest animal" },
  { word: "DESK", clue: "Work surface" },
  { word: "DIAL", clue: "Phone circle" },
  { word: "DICE", clue: "Board game cubes" },
  { word: "DIRT", clue: "Soil" },
  { word: "DISH", clue: "Plate" },
  { word: "DISK", clue: "Flat circle" },
  { word: "DOCK", clue: "Ship berth" },
  { word: "DOME", clue: "Rounded roof" },
  { word: "DONE", clue: "Finished" },
  { word: "DOOR", clue: "Room entrance" },
  { word: "DOSE", clue: "Medicine amount" },
  { word: "DOVE", clue: "Peace bird" },
  { word: "DOWN", clue: "Opposite of up" },
  { word: "DRAG", clue: "Pull along" },
  { word: "DRAW", clue: "Sketch" },
  { word: "DRIP", clue: "Water drop" },
  { word: "DROP", clue: "Let fall" },
  { word: "DRUM", clue: "Beat instrument" },
  { word: "DUAL", clue: "Double" },
  { word: "DUCK", clue: "Pond bird" },
  { word: "DUEL", clue: "One-on-one fight" },
  { word: "DUKE", clue: "Noble rank" },
  { word: "DULL", clue: "Boring" },
  { word: "DUMP", clue: "Trash site" },
  { word: "DUNE", clue: "Sand hill" },
  { word: "DUSK", clue: "Twilight" },
  { word: "DUST", clue: "Fine particles" },
  { word: "DUTY", clue: "Obligation" },
  { word: "EACH", clue: "Every one" },
  { word: "EARN", clue: "Make money" },
  { word: "EASE", clue: "Comfort" },
  { word: "EAST", clue: "Sunrise direction" },
  { word: "EASY", clue: "Not hard" },
  { word: "ECHO", clue: "Sound repeat" },
  { word: "EDGE", clue: "Border" },
  { word: "EDIT", clue: "Revise" },
  { word: "ELSE", clue: "Otherwise" },
  { word: "EPIC", clue: "Grand scale" },
  { word: "EVEN", clue: "Flat or equal" },
  { word: "EVIL", clue: "Wicked" },
  { word: "EXAM", clue: "Test" },
  { word: "EXIT", clue: "Way out" },
  { word: "EXPO", clue: "Exhibition" },
  { word: "FACE", clue: "Front of head" },
  { word: "FACT", clue: "True thing" },
  { word: "FADE", clue: "Lose color" },
  { word: "FAIL", clue: "Not succeed" },
  { word: "FAIR", clue: "Just" },
  { word: "FAKE", clue: "Not real" },
  { word: "FALL", clue: "Autumn" },
  { word: "FAME", clue: "Celebrity" },
  { word: "FARE", clue: "Ticket price" },
  { word: "FARM", clue: "Crop field" },
  { word: "FAST", clue: "Quick" },
  { word: "FATE", clue: "Destiny" },
  { word: "FAWN", clue: "Baby deer" },
  { word: "FEAR", clue: "Fright" },
  { word: "FEED", clue: "Give food" },
  { word: "FEEL", clue: "Touch" },
  { word: "FERN", clue: "Forest plant" },
  { word: "FILE", clue: "Document" },
  { word: "FILL", clue: "Make full" },
  { word: "FILM", clue: "Movie" },
  { word: "FIND", clue: "Discover" },
  { word: "FINE", clue: "Okay or penalty" },
  { word: "FIRE", clue: "Flames" },
  { word: "FIRM", clue: "Solid" },
  { word: "FISH", clue: "Aquatic animal" },
  { word: "FIST", clue: "Clenched hand" },
  { word: "FLAG", clue: "National symbol" },
  { word: "FLAT", clue: "Apartment" },
  { word: "FLAW", clue: "Defect" },
  { word: "FLEA", clue: "Tiny jumper" },
  { word: "FLEW", clue: "Soared" },
  { word: "FLIP", clue: "Turn over" },
  { word: "FLOW", clue: "Stream movement" },
  { word: "FOAM", clue: "Bubble mass" },
  { word: "FOLD", clue: "Bend over" },
  { word: "FOLK", clue: "People" },
  { word: "FOND", clue: "Affectionate" },
  { word: "FOOD", clue: "Nourishment" },
  { word: "FOOL", clue: "Jester" },
  { word: "FOOT", clue: "Bottom of leg" },
  { word: "FORK", clue: "Eating utensil" },
  { word: "FORM", clue: "Shape" },
  { word: "FORT", clue: "Military base" },
  { word: "FOUL", clue: "Rule violation" },
  { word: "FOWL", clue: "Poultry" },
  { word: "FREE", clue: "No cost" },
  { word: "FROG", clue: "Pond hopper" },
  { word: "FROM", clue: "Starting point" },
  { word: "FUEL", clue: "Energy source" },
  { word: "FULL", clue: "Completely filled" },
  { word: "FUND", clue: "Money pool" },
  { word: "FUSE", clue: "Safety device" },
  { word: "FURY", clue: "Intense anger" },
  { word: "GAIN", clue: "Profit" },
  { word: "GALE", clue: "Strong wind" },
  { word: "GAME", clue: "Fun activity" },
  { word: "GATE", clue: "Fence opening" },
  { word: "GAVE", clue: "Donated" },
  { word: "GAZE", clue: "Stare" },
  { word: "GEAR", clue: "Equipment" },
  { word: "GIFT", clue: "Present" },
  { word: "GILD", clue: "Cover in gold" },
  { word: "GLAD", clue: "Happy" },
  { word: "GLOW", clue: "Soft light" },
  { word: "GLUE", clue: "Sticky stuff" },
  { word: "GOAL", clue: "Aim or target" },
  { word: "GOAT", clue: "Mountain animal" },
  { word: "GOLD", clue: "Precious metal" },
  { word: "GOLF", clue: "Club sport" },
  { word: "GONE", clue: "Departed" },
  { word: "GOOD", clue: "Positive" },
  { word: "GRAB", clue: "Seize" },
  { word: "GRAY", clue: "Between black and white" },
  { word: "GREW", clue: "Got bigger" },
  { word: "GRID", clue: "Crossed lines" },
  { word: "GRIM", clue: "Stern" },
  { word: "GRIN", clue: "Big smile" },
  { word: "GRIP", clue: "Firm hold" },
  { word: "GRIT", clue: "Coarse sand" },
  { word: "GROW", clue: "Increase" },
  { word: "GULF", clue: "Bay" },
  { word: "GUST", clue: "Wind burst" },
  { word: "HACK", clue: "Quick fix" },
  { word: "HAIL", clue: "Icy rain" },
  { word: "HAIR", clue: "Head covering" },
  { word: "HALF", clue: "50 percent" },
  { word: "HALL", clue: "Corridor" },
  { word: "HALT", clue: "Stop" },
  { word: "HAND", clue: "Palm and fingers" },
  { word: "HANG", clue: "Suspend" },
  { word: "HARD", clue: "Not soft" },
  { word: "HARE", clue: "Fast rabbit" },
  { word: "HARM", clue: "Damage" },
  { word: "HARP", clue: "String instrument" },
  { word: "HATE", clue: "Despise" },
  { word: "HAUL", clue: "Transport" },
  { word: "HAVE", clue: "Possess" },
  { word: "HAWK", clue: "Bird of prey" },
  { word: "HEAD", clue: "Top of body" },
  { word: "HEAL", clue: "Get better" },
  { word: "HEAP", clue: "Big pile" },
  { word: "HEAR", clue: "Listen" },
  { word: "HEAT", clue: "Warmth" },
  { word: "HEEL", clue: "Back of foot" },
  { word: "HELD", clue: "Gripped" },
  { word: "HELM", clue: "Ship's wheel" },
  { word: "HELP", clue: "Assist" },
  { word: "HERB", clue: "Cooking plant" },
  { word: "HERD", clue: "Group of cattle" },
  { word: "HERE", clue: "In this place" },
  { word: "HERO", clue: "Brave person" },
  { word: "HIDE", clue: "Conceal" },
  { word: "HIGH", clue: "Elevated" },
  { word: "HIKE", clue: "Long walk" },
  { word: "HILL", clue: "Small mountain" },
  { word: "HILT", clue: "Sword handle" },
  { word: "HINT", clue: "Subtle clue" },
  { word: "HIRE", clue: "Employ" },
  { word: "HIVE", clue: "Bee home" },
  { word: "HOLD", clue: "Grasp" },
  { word: "HOLE", clue: "Opening" },
  { word: "HOME", clue: "Where you live" },
  { word: "HOOD", clue: "Head cover" },
  { word: "HOOK", clue: "Curved fastener" },
  { word: "HOPE", clue: "Wish" },
  { word: "HORN", clue: "Bull's weapon" },
  { word: "HOSE", clue: "Garden tube" },
  { word: "HOST", clue: "Party organizer" },
  { word: "HOUR", clue: "60 minutes" },
  { word: "HOWL", clue: "Wolf cry" },
  { word: "HUGE", clue: "Enormous" },
  { word: "HULL", clue: "Ship body" },
  { word: "HUNT", clue: "Search for" },
  { word: "HURT", clue: "Cause pain" },
  { word: "HYMN", clue: "Church song" },
  { word: "IDEA", clue: "Thought" },
  { word: "IDLE", clue: "Not busy" },
  { word: "ICON", clue: "Small image" },
  { word: "IRON", clue: "Press clothes" },
  { word: "ITEM", clue: "Object" },
  { word: "JADE", clue: "Green stone" },
  { word: "JAIL", clue: "Prison" },
  { word: "JAZZ", clue: "Music genre" },
  { word: "JERK", clue: "Quick pull" },
  { word: "JEST", clue: "Joke" },
  { word: "JEWL", clue: "Precious gem" },
  { word: "JOLT", clue: "Sudden shock" },
  { word: "JURY", clue: "Trial panel" },
  { word: "JUST", clue: "Fair" },
  { word: "KEEN", clue: "Eager" },
  { word: "KELP", clue: "Seaweed" },
  { word: "KEPT", clue: "Retained" },
  { word: "KICK", clue: "Foot strike" },
  { word: "KILN", clue: "Pottery oven" },
  { word: "KIND", clue: "Nice" },
  { word: "KING", clue: "Royal ruler" },
  { word: "KITE", clue: "Wind toy" },
  { word: "KNOB", clue: "Door handle" },
  { word: "KNOT", clue: "Tied rope" },
  { word: "KNOW", clue: "Be aware of" },
  { word: "LACE", clue: "Shoe string" },
  { word: "LACK", clue: "Shortage" },
  { word: "LAID", clue: "Put down" },
  { word: "LAKE", clue: "Body of water" },
  { word: "LAMB", clue: "Young sheep" },
  { word: "LAMP", clue: "Light fixture" },
  { word: "LAND", clue: "Solid ground" },
  { word: "LANE", clue: "Narrow road" },
  { word: "LARK", clue: "Songbird" },
  { word: "LASH", clue: "Whip strike" },
  { word: "LAST", clue: "Final" },
  { word: "LATE", clue: "Not on time" },
  { word: "LAWN", clue: "Yard grass" },
  { word: "LEAD", clue: "Guide" },
  { word: "LEAF", clue: "Tree greenery" },
  { word: "LEAK", clue: "Drip out" },
  { word: "LEAN", clue: "Tilt" },
  { word: "LEAP", clue: "Big jump" },
  { word: "LEFT", clue: "Not right" },
  { word: "LEND", clue: "Let borrow" },
  { word: "LENS", clue: "Camera glass" },
  { word: "LESS", clue: "Fewer" },
  { word: "LIFT", clue: "Raise up" },
  { word: "LIKE", clue: "Enjoy" },
  { word: "LIME", clue: "Green citrus" },
  { word: "LIMP", clue: "Walk unevenly" },
  { word: "LINE", clue: "Queue" },
  { word: "LINK", clue: "Connection" },
  { word: "LION", clue: "King of beasts" },
  { word: "LIST", clue: "Item catalog" },
  { word: "LIVE", clue: "Be alive" },
  { word: "LOAD", clue: "Cargo" },
  { word: "LOAF", clue: "Bread shape" },
  { word: "LOAN", clue: "Borrowed money" },
  { word: "LOCK", clue: "Door fastener" },
  { word: "LOGO", clue: "Brand symbol" },
  { word: "LONG", clue: "Extended" },
  { word: "LOOK", clue: "See" },
  { word: "LOOP", clue: "Circle shape" },
  { word: "LORD", clue: "Noble title" },
  { word: "LORE", clue: "Traditional knowledge" },
  { word: "LOSE", clue: "Not win" },
  { word: "LOST", clue: "Can't find way" },
  { word: "LOUD", clue: "Very noisy" },
  { word: "LOVE", clue: "Deep affection" },
  { word: "LUCK", clue: "Good fortune" },
  { word: "LUMP", clue: "Bump" },
  { word: "LUNG", clue: "Breathing organ" },
  { word: "LURE", clue: "Bait" },
  { word: "LURK", clue: "Sneak around" },
  { word: "LUSH", clue: "Green and thick" },

  // ── 5-letter words ──────────────────────────────────────────────
  { word: "ABOUT", clue: "Approximately" },
  { word: "ABOVE", clue: "Higher than" },
  { word: "ADMIT", clue: "Confess" },
  { word: "ADOPT", clue: "Take in" },
  { word: "AFTER", clue: "Following" },
  { word: "AGAIN", clue: "Once more" },
  { word: "AGENT", clue: "Representative" },
  { word: "AGILE", clue: "Nimble" },
  { word: "AGREE", clue: "Say yes" },
  { word: "ALARM", clue: "Warning sound" },
  { word: "ALBUM", clue: "Music collection" },
  { word: "ALERT", clue: "Watchful" },
  { word: "ALIEN", clue: "From outer space" },
  { word: "ALIGN", clue: "Line up" },
  { word: "ALLOW", clue: "Permit" },
  { word: "ALONE", clue: "By yourself" },
  { word: "ALONG", clue: "Beside" },
  { word: "ALTER", clue: "Change" },
  { word: "AMAZE", clue: "Astonish" },
  { word: "AMPLE", clue: "Plenty" },
  { word: "ANGEL", clue: "Heavenly being" },
  { word: "ANGER", clue: "Fury" },
  { word: "ANGLE", clue: "Corner degree" },
  { word: "ANKLE", clue: "Foot joint" },
  { word: "APPLE", clue: "Common fruit" },
  { word: "ARENA", clue: "Sports venue" },
  { word: "ARMOR", clue: "Battle protection" },
  { word: "AROMA", clue: "Pleasant smell" },
  { word: "ASIDE", clue: "To the side" },
  { word: "ATLAS", clue: "Map book" },
  { word: "AVOID", clue: "Stay away from" },
  { word: "AWAKE", clue: "Not sleeping" },
  { word: "BADGE", clue: "ID pin" },
  { word: "BASIC", clue: "Fundamental" },
  { word: "BEACH", clue: "Sandy shore" },
  { word: "BEGIN", clue: "Start" },
  { word: "BEING", clue: "Existence" },
  { word: "BELOW", clue: "Under" },
  { word: "BENCH", clue: "Park seat" },
  { word: "BERRY", clue: "Small fruit" },
  { word: "BIRTH", clue: "Being born" },
  { word: "BLACK", clue: "Darkest color" },
  { word: "BLADE", clue: "Knife edge" },
  { word: "BLAME", clue: "Point finger" },
  { word: "BLANK", clue: "Empty" },
  { word: "BLAST", clue: "Explosion" },
  { word: "BLAZE", clue: "Intense fire" },
  { word: "BLEND", clue: "Mix together" },
  { word: "BLESS", clue: "Give thanks" },
  { word: "BLIND", clue: "Cannot see" },
  { word: "BLOCK", clue: "Solid cube" },
  { word: "BLOOM", clue: "Flower opens" },
  { word: "BLOWN", clue: "Carried by wind" },
  { word: "BOARD", clue: "Flat plank" },
  { word: "BOAST", clue: "Brag" },
  { word: "BONUS", clue: "Extra reward" },
  { word: "BOOTH", clue: "Small enclosure" },
  { word: "BOUND", clue: "Heading toward" },
  { word: "BRAIN", clue: "Thinking organ" },
  { word: "BRAND", clue: "Product name" },
  { word: "BRAVE", clue: "Courageous" },
  { word: "BREAD", clue: "Sandwich base" },
  { word: "BREAK", clue: "Pause" },
  { word: "BRICK", clue: "Building block" },
  { word: "BRIDE", clue: "Wedding woman" },
  { word: "BRIEF", clue: "Short" },
  { word: "BRING", clue: "Carry here" },
  { word: "BROAD", clue: "Wide" },
  { word: "BROOK", clue: "Small stream" },
  { word: "BRUSH", clue: "Painting tool" },
  { word: "BUILD", clue: "Construct" },
  { word: "BURST", clue: "Pop" },
  { word: "CABIN", clue: "Log house" },
  { word: "CANDY", clue: "Sweet treat" },
  { word: "CARGO", clue: "Ship load" },
  { word: "CARRY", clue: "Transport" },
  { word: "CATCH", clue: "Grab" },
  { word: "CAUSE", clue: "Reason" },
  { word: "CEDAR", clue: "Aromatic wood" },
  { word: "CHAIN", clue: "Metal links" },
  { word: "CHAIR", clue: "Sitting furniture" },
  { word: "CHALK", clue: "Board writer" },
  { word: "CHARM", clue: "Attraction" },
  { word: "CHASE", clue: "Run after" },
  { word: "CHEAP", clue: "Low price" },
  { word: "CHECK", clue: "Verify" },
  { word: "CHEEK", clue: "Face side" },
  { word: "CHEER", clue: "Shout support" },
  { word: "CHEST", clue: "Torso front" },
  { word: "CHIEF", clue: "Leader" },
  { word: "CHILD", clue: "Young person" },
  { word: "CHILL", clue: "Cool down" },
  { word: "CHINA", clue: "Fine pottery" },
  { word: "CHOIR", clue: "Singing group" },
  { word: "CHUNK", clue: "Big piece" },
  { word: "CIVIC", clue: "City-related" },
  { word: "CLAIM", clue: "Assert" },
  { word: "CLASH", clue: "Conflict" },
  { word: "CLASP", clue: "Fastening grip" },
  { word: "CLASS", clue: "School group" },
  { word: "CLEAN", clue: "Not dirty" },
  { word: "CLEAR", clue: "Transparent" },
  { word: "CLERK", clue: "Office worker" },
  { word: "CLIMB", clue: "Go up" },
  { word: "CLING", clue: "Hold tight" },
  { word: "CLOCK", clue: "Time teller" },
  { word: "CLONE", clue: "Exact copy" },
  { word: "CLOSE", clue: "Shut" },
  { word: "CLOTH", clue: "Fabric" },
  { word: "CLOUD", clue: "Sky puff" },
  { word: "COACH", clue: "Team trainer" },
  { word: "COAST", clue: "Shoreline" },
  { word: "COLOR", clue: "Hue" },
  { word: "CORAL", clue: "Reef builder" },
  { word: "COUCH", clue: "Living room seat" },
  { word: "COUNT", clue: "Number up" },
  { word: "COURT", clue: "Tennis area" },
  { word: "COVER", clue: "Put on top" },
  { word: "CRAFT", clue: "Skill or boat" },
  { word: "CRANE", clue: "Building lifter" },
  { word: "CRASH", clue: "Collision" },
  { word: "CRAWL", clue: "Move on hands" },
  { word: "CRAZY", clue: "Insane" },
  { word: "CREAM", clue: "Coffee addition" },
  { word: "CREST", clue: "Wave top" },
  { word: "CRIME", clue: "Illegal act" },
  { word: "CRISP", clue: "Fresh and firm" },
  { word: "CROSS", clue: "Go across" },
  { word: "CROWD", clue: "Large group" },
  { word: "CROWN", clue: "King's headwear" },
  { word: "CRUEL", clue: "Mean" },
  { word: "CRUSH", clue: "Squash" },
  { word: "CUBIC", clue: "Box-shaped" },
  { word: "CYCLE", clue: "Repeat pattern" },
  { word: "DAILY", clue: "Every day" },
  { word: "DANCE", clue: "Move to music" },
  { word: "DEALT", clue: "Handed out cards" },
  { word: "DECAY", clue: "Rot" },
  { word: "DELTA", clue: "River mouth" },
  { word: "DEMON", clue: "Evil spirit" },
  { word: "DENSE", clue: "Thick" },
  { word: "DEPOT", clue: "Storage station" },
  { word: "DEPTH", clue: "Deepness" },
  { word: "DERBY", clue: "Horse race" },
  { word: "DIGIT", clue: "Number 0-9" },
  { word: "DOING", clue: "Performing" },
  { word: "DOUBT", clue: "Uncertainty" },
  { word: "DOUGH", clue: "Bread base" },
  { word: "DRAFT", clue: "First version" },
  { word: "DRAIN", clue: "Water exit" },
  { word: "DRAMA", clue: "Theater art" },
  { word: "DRANK", clue: "Had a sip" },
  { word: "DRAWN", clue: "Sketched" },
  { word: "DREAM", clue: "Sleep vision" },
  { word: "DRESS", clue: "Woman's garment" },
  { word: "DRIED", clue: "Not wet anymore" },
  { word: "DRIFT", clue: "Float along" },
  { word: "DRILL", clue: "Boring tool" },
  { word: "DRINK", clue: "Beverage" },
  { word: "DRIVE", clue: "Operate a car" },
  { word: "DRONE", clue: "Flying robot" },
  { word: "DROWN", clue: "Sink underwater" },
  { word: "DRYER", clue: "Clothes machine" },
  { word: "DUSTY", clue: "Covered in dust" },
  { word: "DWARF", clue: "Very small person" },
  { word: "DWELL", clue: "Live in" },
  { word: "EAGER", clue: "Very keen" },
  { word: "EAGLE", clue: "Majestic bird" },
  { word: "EARLY", clue: "Before time" },
  { word: "EARTH", clue: "Our planet" },
  { word: "EIGHT", clue: "Number after seven" },
  { word: "ELBOW", clue: "Arm joint" },
  { word: "ELDER", clue: "Older person" },
  { word: "ELECT", clue: "Vote for" },
  { word: "ELITE", clue: "Top class" },
  { word: "EMBED", clue: "Fix firmly" },
  { word: "EMPTY", clue: "Nothing inside" },
  { word: "ENJOY", clue: "Have fun" },
  { word: "ENTER", clue: "Go in" },
  { word: "EQUAL", clue: "Same" },
  { word: "ERASE", clue: "Wipe clean" },
  { word: "ERROR", clue: "Mistake" },
  { word: "EVENT", clue: "Happening" },
  { word: "EVERY", clue: "Each one" },
  { word: "EXACT", clue: "Precise" },
  { word: "EXIST", clue: "Be real" },
  { word: "EXTRA", clue: "Additional" },
  { word: "FABLE", clue: "Moral story" },
  { word: "FAITH", clue: "Belief" },
  { word: "FALSE", clue: "Not true" },
  { word: "FANCY", clue: "Elegant" },
  { word: "FAULT", clue: "Blame" },
  { word: "FEAST", clue: "Big meal" },
  { word: "FENCE", clue: "Yard border" },
  { word: "FEVER", clue: "High temperature" },
  { word: "FIBER", clue: "Thread material" },
  { word: "FIELD", clue: "Open land" },
  { word: "FIFTY", clue: "Half of hundred" },
  { word: "FIGHT", clue: "Battle" },
  { word: "FINAL", clue: "Last" },
  { word: "FLAME", clue: "Fire tongue" },
  { word: "FLASH", clue: "Quick light" },
  { word: "FLEET", clue: "Ship group" },
  { word: "FLESH", clue: "Body tissue" },
  { word: "FLOAT", clue: "Stay on water" },
  { word: "FLOCK", clue: "Bird group" },
  { word: "FLOOD", clue: "Water overflow" },
  { word: "FLOOR", clue: "Walk on it" },
  { word: "FLORA", clue: "Plant life" },
  { word: "FLOUR", clue: "Baking powder" },
  { word: "FLOWN", clue: "Gone by air" },
  { word: "FLUID", clue: "Liquid" },
  { word: "FLUTE", clue: "Wind instrument" },
  { word: "FOCUS", clue: "Concentrate" },
  { word: "FORCE", clue: "Power" },
  { word: "FORGE", clue: "Blacksmith shop" },
  { word: "FORTY", clue: "Four tens" },
  { word: "FORUM", clue: "Discussion place" },
  { word: "FOUND", clue: "Discovered" },
  { word: "FRAME", clue: "Picture border" },
  { word: "FRANK", clue: "Honest" },
  { word: "FRESH", clue: "Newly made" },
  { word: "FROST", clue: "Icy coating" },
  { word: "FRUIT", clue: "Apple or banana" },
  { word: "GIANT", clue: "Very large" },
  { word: "GIVEN", clue: "Handed over" },
  { word: "GLASS", clue: "Drinking vessel" },
  { word: "GLOBE", clue: "World model" },
  { word: "GLOOM", clue: "Darkness" },
  { word: "GLOSS", clue: "Shiny finish" },
  { word: "GLOVE", clue: "Hand cover" },
  { word: "GOOSE", clue: "Honking bird" },
  { word: "GRACE", clue: "Elegance" },
  { word: "GRADE", clue: "School mark" },
  { word: "GRAIN", clue: "Cereal seed" },
  { word: "GRAND", clue: "Magnificent" },
  { word: "GRANT", clue: "Give funding" },
  { word: "GRAPE", clue: "Wine fruit" },
  { word: "GRASP", clue: "Grip tightly" },
  { word: "GRASS", clue: "Lawn green" },
  { word: "GRAVE", clue: "Burial site" },
  { word: "GREAT", clue: "Wonderful" },
  { word: "GREEN", clue: "Grass color" },
  { word: "GREET", clue: "Say hello" },
  { word: "GRIEF", clue: "Deep sadness" },
  { word: "GRIND", clue: "Crush fine" },
  { word: "GROSS", clue: "Disgusting" },
  { word: "GROUP", clue: "Collection" },
  { word: "GROVE", clue: "Small forest" },
  { word: "GUARD", clue: "Protector" },
  { word: "GUESS", clue: "Estimate" },
  { word: "GUEST", clue: "Visitor" },
  { word: "GUIDE", clue: "Show the way" },
  { word: "GUILT", clue: "Remorse" },
  { word: "HABIT", clue: "Routine" },
  { word: "HAPPY", clue: "Joyful" },
  { word: "HARSH", clue: "Severe" },
  { word: "HEART", clue: "Blood pump" },
  { word: "HEAVY", clue: "Weighs a lot" },
  { word: "HEDGE", clue: "Garden border" },
  { word: "HELLO", clue: "Greeting" },
  { word: "HONEY", clue: "Bee product" },
  { word: "HORSE", clue: "Riding animal" },
  { word: "HOTEL", clue: "Guest lodging" },
  { word: "HOUSE", clue: "Home" },
  { word: "HUMAN", clue: "Person" },
  { word: "HUMOR", clue: "Comedy" },
  { word: "IDEAL", clue: "Perfect" },
  { word: "IMAGE", clue: "Picture" },
  { word: "IMPLY", clue: "Suggest" },
  { word: "INDEX", clue: "Book guide" },
  { word: "INNER", clue: "Inside" },
  { word: "INPUT", clue: "Data entry" },
  { word: "ISSUE", clue: "Problem" },
  { word: "IVORY", clue: "Tusk material" },
  { word: "JEWEL", clue: "Precious stone" },
  { word: "JOINT", clue: "Body hinge" },
  { word: "JUDGE", clue: "Court official" },
  { word: "JUICE", clue: "Fruit drink" },
  { word: "KNACK", clue: "Special skill" },
  { word: "KNEEL", clue: "Bend the knee" },
  { word: "KNIFE", clue: "Cutting tool" },
  { word: "KNOCK", clue: "Rap on door" },
  { word: "LABEL", clue: "Name tag" },
  { word: "LARGE", clue: "Big" },
  { word: "LASER", clue: "Focused beam" },
  { word: "LATER", clue: "Afterward" },
  { word: "LAYER", clue: "One thickness" },
  { word: "LEARN", clue: "Gain knowledge" },
  { word: "LEASE", clue: "Rent agreement" },
  { word: "LEVEL", clue: "Flat surface" },
  { word: "LIGHT", clue: "Illumination" },
  { word: "LIMIT", clue: "Boundary" },
  { word: "LINEN", clue: "Bed fabric" },
  { word: "LIVER", clue: "Body organ" },
  { word: "LOCAL", clue: "Nearby" },
  { word: "LOGIC", clue: "Reasoning" },
  { word: "LOOSE", clue: "Not tight" },
  { word: "LOVER", clue: "Romantic partner" },
  { word: "LOWER", clue: "Bring down" },
  { word: "LUNAR", clue: "Moon-related" },
  { word: "LUNCH", clue: "Midday meal" },
  { word: "MAGIC", clue: "Wizardry" },
  { word: "MAJOR", clue: "Significant" },
  { word: "MAKER", clue: "Creator" },
  { word: "MANOR", clue: "Large estate" },
  { word: "MARCH", clue: "Third month" },
  { word: "MATCH", clue: "Game or pair" },
  { word: "MAYOR", clue: "City leader" },
  { word: "MEDAL", clue: "Award disc" },
  { word: "MEDIA", clue: "News outlets" },
  { word: "MERCY", clue: "Compassion" },
  { word: "MERGE", clue: "Combine" },
  { word: "MERIT", clue: "Worth" },
  { word: "MERRY", clue: "Cheerful" },
  { word: "METAL", clue: "Iron or steel" },
  { word: "METER", clue: "Measuring unit" },
  { word: "MIGHT", clue: "Power" },
  { word: "MINOR", clue: "Small or young" },
  { word: "MODEL", clue: "Example" },
  { word: "MONEY", clue: "Currency" },
  { word: "MONTH", clue: "Year division" },
  { word: "MORAL", clue: "Ethical" },
  { word: "MOTOR", clue: "Engine" },
  { word: "MOUNT", clue: "Climb up" },
  { word: "MOUSE", clue: "Computer pointer" },
  { word: "MOUTH", clue: "Face opening" },
  { word: "MOVIE", clue: "Film" },
  { word: "MUDDY", clue: "Covered in mud" },
  { word: "MUSIC", clue: "Melody" },
  { word: "NAVAL", clue: "Navy-related" },
  { word: "NERVE", clue: "Body fiber" },
  { word: "NEVER", clue: "Not ever" },
  { word: "NIGHT", clue: "After sunset" },
  { word: "NOBLE", clue: "Honorable" },
  { word: "NOISE", clue: "Unwanted sound" },
  { word: "NORTH", clue: "Compass direction" },
  { word: "NOTED", clue: "Famous" },
  { word: "NOVEL", clue: "Long book" },
  { word: "NURSE", clue: "Hospital worker" },
  { word: "OCCUR", clue: "Happen" },
  { word: "OCEAN", clue: "Vast water body" },
  { word: "OFFER", clue: "Propose" },
  { word: "OFTEN", clue: "Frequently" },
  { word: "OLIVE", clue: "Pizza topping" },
  { word: "ONION", clue: "Cry vegetable" },
  { word: "OPERA", clue: "Singing drama" },
  { word: "ORDER", clue: "Arrangement" },
  { word: "ORGAN", clue: "Body part" },
  { word: "OTHER", clue: "Different one" },
  { word: "OUTER", clue: "External" },
  { word: "OWNER", clue: "Possessor" },
  { word: "OXIDE", clue: "Rust compound" },
  { word: "PANDA", clue: "Black and white bear" },
  { word: "PANEL", clue: "Flat board" },
  { word: "PANIC", clue: "Sudden fear" },
  { word: "PAPER", clue: "Writing sheet" },
  { word: "PATCH", clue: "Repair piece" },
  { word: "PAUSE", clue: "Brief stop" },
  { word: "PEACE", clue: "No war" },
  { word: "PEARL", clue: "Oyster gem" },
  { word: "PHASE", clue: "Stage" },
  { word: "PHONE", clue: "Calling device" },
  { word: "PHOTO", clue: "Picture" },
  { word: "PIANO", clue: "Keyboard instrument" },
  { word: "PIECE", clue: "Part" },
  { word: "PILOT", clue: "Plane driver" },
  { word: "PITCH", clue: "Throw" },
  { word: "PIXEL", clue: "Screen dot" },
  { word: "PLACE", clue: "Location" },
  { word: "PLAIN", clue: "Simple" },
  { word: "PLANE", clue: "Aircraft" },
  { word: "PLANT", clue: "Growing thing" },
  { word: "PLATE", clue: "Dinner dish" },
  { word: "PLAZA", clue: "Town square" },
  { word: "PLEAD", clue: "Beg" },
  { word: "PLUMB", clue: "Check vertical" },
  { word: "PLUME", clue: "Feather" },
  { word: "POINT", clue: "Sharp end" },
  { word: "POLAR", clue: "Arctic region" },
  { word: "POUND", clue: "Weight unit" },
  { word: "POWER", clue: "Strength" },
  { word: "PRESS", clue: "Push down" },
  { word: "PRICE", clue: "Cost" },
  { word: "PRIDE", clue: "Self-respect" },
  { word: "PRIME", clue: "First rate" },
  { word: "PRINT", clue: "Put on paper" },
  { word: "PRIOR", clue: "Before" },
  { word: "PRIZE", clue: "Award" },
  { word: "PROOF", clue: "Evidence" },
  { word: "PROUD", clue: "Full of pride" },
  { word: "PROVE", clue: "Show true" },
  { word: "PULSE", clue: "Heartbeat" },
  { word: "PUPIL", clue: "Student" },
  { word: "QUEEN", clue: "Female ruler" },
  { word: "QUERY", clue: "Question" },
  { word: "QUEST", clue: "Search journey" },
  { word: "QUICK", clue: "Fast" },
  { word: "QUIET", clue: "Silent" },
  { word: "QUOTA", clue: "Limit amount" },
  { word: "QUOTE", clue: "Repeat words" },
  { word: "RADAR", clue: "Detection system" },
  { word: "RADIO", clue: "Audio broadcast" },
  { word: "RAISE", clue: "Lift up" },
  { word: "RALLY", clue: "Come together" },
  { word: "RANCH", clue: "Cattle farm" },
  { word: "RANGE", clue: "Variety" },
  { word: "RAPID", clue: "Very fast" },
  { word: "RATIO", clue: "Proportion" },
  { word: "REACH", clue: "Extend to" },
  { word: "READY", clue: "Prepared" },
  { word: "REALM", clue: "Kingdom" },
  { word: "REBEL", clue: "Resist authority" },
  { word: "REFER", clue: "Direct to" },
  { word: "RELAX", clue: "Unwind" },
  { word: "RELAY", clue: "Pass along" },
  { word: "REPLY", clue: "Answer" },
  { word: "RIDER", clue: "Horse jockey" },
  { word: "RIDGE", clue: "Mountain top" },
  { word: "RIGHT", clue: "Correct" },
  { word: "RIGID", clue: "Stiff" },
  { word: "RISKY", clue: "Dangerous" },
  { word: "RIVAL", clue: "Competitor" },
  { word: "RIVER", clue: "Flowing water" },
  { word: "ROAST", clue: "Cook in oven" },
  { word: "ROBOT", clue: "Mechanical being" },
  { word: "ROCKY", clue: "Full of stones" },
  { word: "ROUGE", clue: "Red cosmetic" },
  { word: "ROUND", clue: "Circular" },
  { word: "ROUTE", clue: "Path taken" },
  { word: "ROYAL", clue: "King's family" },
  { word: "RULER", clue: "Measuring stick" },
  { word: "RURAL", clue: "Countryside" },
  { word: "SADLY", clue: "With sorrow" },
  { word: "SAINT", clue: "Holy person" },
  { word: "SALAD", clue: "Green dish" },
  { word: "SCALE", clue: "Weight device" },
  { word: "SCARE", clue: "Frighten" },
  { word: "SCENE", clue: "Movie part" },
  { word: "SCENT", clue: "Fragrance" },
  { word: "SCOPE", clue: "Range" },
  { word: "SCORE", clue: "Game points" },
  { word: "SCOUT", clue: "Explorer" },
  { word: "SERVE", clue: "Wait on" },
  { word: "SEVEN", clue: "Lucky number" },
  { word: "SHADE", clue: "Shadow area" },
  { word: "SHALL", clue: "Will (formal)" },
  { word: "SHAME", clue: "Disgrace" },
  { word: "SHAPE", clue: "Form" },
  { word: "SHARE", clue: "Divide up" },
  { word: "SHARK", clue: "Ocean predator" },
  { word: "SHARP", clue: "Very pointy" },
  { word: "SHELF", clue: "Book holder" },
  { word: "SHELL", clue: "Beach find" },
  { word: "SHIFT", clue: "Work period" },
  { word: "SHINE", clue: "Gleam" },
  { word: "SHIRT", clue: "Upper garment" },
  { word: "SHOCK", clue: "Surprise" },
  { word: "SHORE", clue: "Water edge" },
  { word: "SHORT", clue: "Not tall" },
  { word: "SHOUT", clue: "Yell" },
  { word: "SIGHT", clue: "Vision" },
  { word: "SINCE", clue: "From then" },
  { word: "SIXTH", clue: "After fifth" },
  { word: "SIXTY", clue: "Six tens" },
  { word: "SKILL", clue: "Ability" },
  { word: "SKIRT", clue: "Woman's garment" },
  { word: "SKULL", clue: "Head bone" },
  { word: "SLASH", clue: "Cut swiftly" },
  { word: "SLATE", clue: "Roof tile" },
  { word: "SLEEP", clue: "Night rest" },
  { word: "SLICE", clue: "Thin cut" },
  { word: "SLIDE", clue: "Playground ride" },
  { word: "SLOPE", clue: "Hill angle" },
  { word: "SMALL", clue: "Tiny" },
  { word: "SMART", clue: "Clever" },
  { word: "SMELL", clue: "Use your nose" },
  { word: "SMILE", clue: "Happy face" },
  { word: "SMOKE", clue: "Fire fumes" },
  { word: "SNACK", clue: "Light bite" },
  { word: "SNAKE", clue: "Slithering reptile" },
  { word: "SOLAR", clue: "Sun-powered" },
  { word: "SOLID", clue: "Not liquid" },
  { word: "SOLVE", clue: "Find answer" },
  { word: "SOUTH", clue: "Opposite of north" },
  { word: "SPACE", clue: "Outer cosmos" },
  { word: "SPARE", clue: "Extra" },
  { word: "SPARK", clue: "Tiny fire" },
  { word: "SPEAK", clue: "Talk" },
  { word: "SPEED", clue: "Velocity" },
  { word: "SPEND", clue: "Use money" },
  { word: "SPICE", clue: "Food seasoning" },
  { word: "SPOKE", clue: "Wheel rod" },
  { word: "SPORT", clue: "Athletic game" },
  { word: "SPRAY", clue: "Mist" },
  { word: "SQUAD", clue: "Small team" },
  { word: "STACK", clue: "Pile up" },
  { word: "STAFF", clue: "Employees" },
  { word: "STAGE", clue: "Theater platform" },
  { word: "STAIN", clue: "Permanent mark" },
  { word: "STAIR", clue: "Step" },
  { word: "STAKE", clue: "Claim or bet" },
  { word: "STALE", clue: "Not fresh" },
  { word: "STALL", clue: "Market booth" },
  { word: "STAMP", clue: "Mail mark" },
  { word: "STAND", clue: "Be upright" },
  { word: "STARE", clue: "Long look" },
  { word: "START", clue: "Begin" },
  { word: "STATE", clue: "Country region" },
  { word: "STEAM", clue: "Hot water vapor" },
  { word: "STEEL", clue: "Strong metal" },
  { word: "STEEP", clue: "Very angled" },
  { word: "STEER", clue: "Guide direction" },
  { word: "STERN", clue: "Ship back" },
  { word: "STICK", clue: "Branch" },
  { word: "STILL", clue: "Not moving" },
  { word: "STOCK", clue: "Supply" },
  { word: "STONE", clue: "Rock" },
  { word: "STOOD", clue: "Was upright" },
  { word: "STORE", clue: "Shop" },
  { word: "STORM", clue: "Rough weather" },
  { word: "STORY", clue: "Tale" },
  { word: "STOVE", clue: "Cooking appliance" },
  { word: "STRIP", clue: "Narrow piece" },
  { word: "STUCK", clue: "Can't move" },
  { word: "STUDY", clue: "Learn" },
  { word: "STUFF", clue: "Things" },
  { word: "STYLE", clue: "Fashion" },
  { word: "SUGAR", clue: "Sweet crystal" },
  { word: "SUITE", clue: "Hotel room set" },
  { word: "SUPER", clue: "Excellent" },
  { word: "SURGE", clue: "Sudden increase" },
  { word: "SWEEP", clue: "Clean floor" },
  { word: "SWEET", clue: "Sugary" },
  { word: "SWIFT", clue: "Very quick" },
  { word: "SWING", clue: "Playground ride" },
  { word: "SWORD", clue: "Knight's weapon" },
  { word: "TABLE", clue: "Eating surface" },
  { word: "TEACH", clue: "Educate" },
  { word: "THANK", clue: "Show gratitude" },
  { word: "THEME", clue: "Central topic" },
  { word: "THICK", clue: "Not thin" },
  { word: "THING", clue: "Object" },
  { word: "THINK", clue: "Use your brain" },
  { word: "THIRD", clue: "After second" },
  { word: "THORN", clue: "Rose prickle" },
  { word: "THOSE", clue: "Them over there" },
  { word: "THREE", clue: "After two" },
  { word: "THREW", clue: "Tossed" },
  { word: "THROW", clue: "Toss" },
  { word: "THUMB", clue: "Short finger" },
  { word: "TIDAL", clue: "Wave-related" },
  { word: "TIGER", clue: "Striped cat" },
  { word: "TIGHT", clue: "Snug fit" },
  { word: "TIMER", clue: "Countdown device" },
  { word: "TITLE", clue: "Name of work" },
  { word: "TODAY", clue: "This day" },
  { word: "TOKEN", clue: "Symbol piece" },
  { word: "TOTAL", clue: "Sum" },
  { word: "TOUCH", clue: "Feel" },
  { word: "TOUGH", clue: "Hard" },
  { word: "TOWER", clue: "Tall structure" },
  { word: "TOXIC", clue: "Poisonous" },
  { word: "TRACE", clue: "Faint mark" },
  { word: "TRACK", clue: "Running path" },
  { word: "TRADE", clue: "Exchange" },
  { word: "TRAIL", clue: "Hiking path" },
  { word: "TRAIN", clue: "Railroad vehicle" },
  { word: "TRAIT", clue: "Characteristic" },
  { word: "TREAT", clue: "Special gift" },
  { word: "TREND", clue: "Fashion direction" },
  { word: "TRIAL", clue: "Court case" },
  { word: "TRIBE", clue: "Native group" },
  { word: "TRICK", clue: "Clever act" },
  { word: "TRIED", clue: "Attempted" },
  { word: "TROOP", clue: "Soldier group" },
  { word: "TRUCK", clue: "Heavy vehicle" },
  { word: "TRULY", clue: "Really" },
  { word: "TRUMP", clue: "Winning card" },
  { word: "TRUNK", clue: "Tree base" },
  { word: "TRUST", clue: "Have faith" },
  { word: "TRUTH", clue: "Fact" },
  { word: "TULIP", clue: "Spring flower" },
  { word: "TUMOR", clue: "Abnormal growth" },
  { word: "TWICE", clue: "Two times" },
  { word: "TWIST", clue: "Turn" },
  { word: "ULTRA", clue: "Extreme" },
  { word: "UNDER", clue: "Below" },
  { word: "UNION", clue: "Workers' group" },
  { word: "UNITE", clue: "Join together" },
  { word: "UNITY", clue: "Togetherness" },
  { word: "UNTIL", clue: "Up to" },
  { word: "UPPER", clue: "Higher part" },
  { word: "UPSET", clue: "Disturbed" },
  { word: "URBAN", clue: "City-like" },
  { word: "USAGE", clue: "How it's used" },
  { word: "USUAL", clue: "Normal" },
  { word: "VALID", clue: "Acceptable" },
  { word: "VALUE", clue: "Worth" },
  { word: "VALVE", clue: "Flow controller" },
  { word: "VAPOR", clue: "Steam" },
  { word: "VAULT", clue: "Secure room" },
  { word: "VERSE", clue: "Poem line" },
  { word: "VIDEO", clue: "Moving pictures" },
  { word: "VIGOR", clue: "Energy" },
  { word: "VINYL", clue: "Record material" },
  { word: "VIOLA", clue: "String instrument" },
  { word: "VIRAL", clue: "Spreading fast" },
  { word: "VISIT", clue: "Go see" },
  { word: "VITAL", clue: "Essential" },
  { word: "VIVID", clue: "Bright" },
  { word: "VOCAL", clue: "Sung" },
  { word: "VOICE", clue: "Speaking sound" },
  { word: "VOTER", clue: "Election participant" },
  { word: "WAIST", clue: "Belt area" },
  { word: "WASTE", clue: "Garbage" },
  { word: "WATCH", clue: "Wrist timepiece" },
  { word: "WATER", clue: "H2O" },
  { word: "WEAVE", clue: "Interlace threads" },
  { word: "WHEAT", clue: "Bread grain" },
  { word: "WHEEL", clue: "Round roller" },
  { word: "WHERE", clue: "What place" },
  { word: "WHILE", clue: "During" },
  { word: "WHITE", clue: "Snow color" },
  { word: "WHOLE", clue: "Complete" },
  { word: "WIDER", clue: "More broad" },
  { word: "WITCH", clue: "Broomstick rider" },
  { word: "WORLD", clue: "Earth" },
  { word: "WORTH", clue: "Value" },
  { word: "WOULD", clue: "Might" },
  { word: "WOUND", clue: "Injury" },
  { word: "WRIST", clue: "Hand joint" },
  { word: "WROTE", clue: "Penned" },
  { word: "YACHT", clue: "Luxury boat" },
  { word: "YIELD", clue: "Give way" },
  { word: "YOUNG", clue: "Not old" },
  { word: "YOUTH", clue: "Young age" },
  { word: "ZEBRA", clue: "Striped horse" },
];

// ── Indexed lookups (built at module load) ──────────────────────────────

export const wordsByLength: Map<number, WordEntry[]> = new Map();
export const clueByWord: Map<string, string> = new Map();

for (const entry of WORD_BANK) {
  const len = entry.word.length;
  if (!wordsByLength.has(len)) wordsByLength.set(len, []);
  wordsByLength.get(len)!.push(entry);
  clueByWord.set(entry.word, entry.clue);
}
