-- CreateEnum
CREATE TYPE "HKStaffType" AS ENUM ('HOUSEKEEPING', 'PLUMBER', 'ELECTRICIAN', 'HELPER');

-- AlterTable
ALTER TABLE "HKStaff" ADD COLUMN     "type" "HKStaffType" NOT NULL DEFAULT 'HOUSEKEEPING';
